const actividades = [
  {
    id: 1,
    inicio: "2025-03-28T12:00",
    termino: "2025-03-28T14:00",
    region: "Metropolitana",
    comuna: "Santiago",
    sector: "Beauchef 850, terraza",
    tema: "Escuela de Boxeo",
    organizador: "Juan Pérez",
    email: "juan@example.com",
    celular: "+569.12345678",
    contacto: { tipo: "whatsapp", id: "123456789" },
    descripcion: "Una escuela de boxeo para todos.",
    fotos: ["foto1.jpg"],
  },
  {
    id: 2,
    inicio: "2025-03-29T19:00",
    termino: "2025-03-29T20:00",
    region: "Metropolitana",
    comuna: "Ñuñoa",
    sector: "Plaza",
    tema: "Cómo deshidratar fruta",
    organizador: "María Gómez",
    email: "maria@example.com",
    celular: "",
    contacto: { tipo: "", id: "" },
    descripcion: "Taller práctico.",
    fotos: ["foto2.jpg"],
  },
  {
    id: 3,
    inicio: "2025-03-30T18:00",
    termino: "",
    region: "Metropolitana",
    comuna: "Santiago",
    sector: "Parque O'higgins",
    tema: "música urbana",
    organizador: "Pedro López",
    email: "pedro@example.com",
    celular: "+569.87654321",
    contacto: { tipo: "instagram", id: "pedro_music" },
    descripcion: "Concierto al aire libre.",
    fotos: ["foto3.jpg"],
  },
  {
    id: 4,
    inicio: "2025-03-31T18:00",
    termino: "",
    region: "Metropolitana",
    comuna: "Santiago",
    sector: "Parque O'higgins",
    tema: "música eletronica",
    organizador: "Pedro Sampaio",
    email: "pedro@example.com",
    celular: "+569.87654321",
    contacto: { tipo: "instagram", id: "pedro_music" },
    descripcion: "Concierto al aire libre.",
    fotos: ["foto4.jpeg"],
  },
  {
    id: 5,
    inicio: "2025-04-01T18:00",
    termino: "",
    region: "Metropolitana",
    comuna: "Santiago",
    sector: "Parque O'higgins",
    tema: "festival de musica",
    organizador: "Bruno Silva",
    email: "bruno@example.com",
    celular: "+569.87654321",
    contacto: { tipo: "instagram", id: "bruno" },
    descripcion: "Concierto al aire libre.",
    fotos: ["foto5.jpeg"],
  },
];
